# Blocks to track individually by material name
tracked-blocks:
  - NETHER_QUARTZ_ORE
  - ANCIENT_DEBRIS

# Tags to track (tracks all blocks in the tag)
# https://mcreator.net/wiki/minecraft-block-tags-list
tracked-tags:
  - diamond_ores
  - gold_ores
  - iron_ores
  - coal_ores
  - copper_ores
  - emerald_ores
  - lapis_ores
  - redstone_ores